name: Image Upload

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Image file name'
        required: true
      base64image:
        description: 'Base64 encoded image content'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Save image
        run: |
          echo "${{ github.event.inputs.base64image }}" | base64 --decode > uploads/${{ github.event.inputs.filename }}

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add uploads/${{ github.event.inputs.filename }}
          git commit -m "Upload ${{ github.event.inputs.filename }}"
          git push
